# Generated by Django 4.1.6 on 2023-02-26 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_post_likes_delete_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="followstatus",
        ),
    ]
