# Generated by Django 4.1.7 on 2023-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockcalculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoholding",
            name="type",
            field=models.CharField(
                choices=[
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Interest", "Interest"),
                    ("Deduction", "Deduction"),
                    ("Deposit", "Deposit"),
                    ("Withdrawal", "Withdrawal"),
                ],
                default="Interest",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fiatholding",
            name="type",
            field=models.CharField(
                choices=[
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Interest", "Interest"),
                    ("Deduction", "Deduction"),
                    ("Deposit", "Deposit"),
                    ("Withdrawal", "Withdrawal"),
                ],
                default="Interest",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
