# Generated by Django 4.1.7 on 2023-04-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockcalculator", "0002_cryptoholding_type_fiatholding_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockholding",
            name="selltransactions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="relatedbuytransactions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fiatholding",
            name="type",
            field=models.CharField(
                choices=[
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Interest", "Interest"),
                    ("Deduction", "Deduction"),
                    ("Deposit", "Deposit"),
                    ("Withdrawal", "Withdrawal"),
                    ("Stockbuy", "Stockbuy"),
                    ("Stocksell", "Stocksell"),
                ],
                max_length=10,
            ),
        ),
    ]
