# Generated by Django 4.1.7 on 2023-04-13 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stockcalculator", "0003_stockholding_selltransactions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="relatedbuytransactions",
            new_name="relatedstockholdings",
        ),
    ]
