# Generated by Django 4.1.7 on 2023-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stockcalculator",
            "0004_rename_relatedbuytransactions_transaction_relatedstockholdings",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockholding",
            name="selltransactions",
        ),
        migrations.AddField(
            model_name="stockholding",
            name="original_quantity",
            field=models.DecimalField(decimal_places=30, default=9999, max_digits=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockholding",
            name="price",
            field=models.DecimalField(decimal_places=30, max_digits=60),
        ),
        migrations.AlterField(
            model_name="stockholding",
            name="quantity",
            field=models.DecimalField(decimal_places=30, max_digits=60),
        ),
    ]
