# Generated by Django 4.1.7 on 2023-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockcalculator", "0005_remove_stockholding_selltransactions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoholding",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fiatholding",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockholding",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
