# Generated by Django 4.1.7 on 2023-04-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockcalculator", "0006_cryptoholding_deleted_fiatholding_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptoholding",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="fiatholding",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="stockholding",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="deleted",
        ),
        migrations.AddField(
            model_name="cryptoholding",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="fiatholding",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="stockholding",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
