# Generated by Django 4.1.7 on 2023-04-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockcalculator", "0007_remove_cryptoholding_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockholding",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
